# Generated by Django 4.0.5 on 2022-06-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='movie name')),
                ('production_year', models.IntegerField(verbose_name='production year')),
                ('create_time', models.TimeField(auto_now=True, verbose_name='Created at')),
                ('update_time', models.TimeField(auto_now=True, verbose_name='Updated at')),
                ('actors', models.ManyToManyField(to='actors.actor')),
            ],
        ),
    ]
